fix discovery teardown
opencontainers/distribution-spec pull request #479
Opened 2023-10-10 05:45 UTC by waynr

Discovery test teardown was broken prior to this because it would attempt to
delete a blob before deleting at least five manifests left over from the setup
that still reference it. Most registries probably don't care about deleting
content that's referenced by other content, which is probably why this works
for others.

Also, I was seeing `GET /v2/<name>/tags/list?n=0` requests and then out of
bounds indexing into the resulting slice because of the weird logic used to
calculate what the `n` parameter should be in the tag listing endpoint tests.

2023-10-12 18:04 UTC, mikebrow commented
pls sign commits

2023-10-13 01:03 UTC, sudo-bmitch requested changes
Couple minor changes to align all the manifests.

2023-10-13 01:03 UTC, sudo-bmitch commented on conformance/03_discovery_test.go
> +						manifests[2].Digest,
Add `manifests[4]`:

```suggestion
						manifests[2].Digest,
						manifests[4].Digest,
```

2023-10-13 01:03 UTC, sudo-bmitch commented on conformance/03_discovery_test.go
> +						manifests[2].Digest,
```suggestion
						manifests[2].Digest,
						manifests[4].Digest,
```

2023-10-13 01:03 UTC, sudo-bmitch commented on conformance/03_discovery_test.go
> +						refsManifestAConfigArtifactDigest,
```suggestion
```

2023-11-10 21:57 UTC, sudo-bmitch commented
@waynr do you have time to work on the changes requested? If not, I can take a stab at it.

2023-11-11 00:52 UTC, waynr commented
@sudo-bmitch I accepted your suggested changes, thanks for the reminder!

2023-11-13 14:27 UTC, jdolitsky approved these changes

2023-11-13 14:27 UTC, merged