spec: clarify referrers response for index
opencontainers/distribution-spec pull request #500
Opened 2023-12-21 21:42 UTC by sajayantony

Addresses : #458 
@sudo-bmitch

2023-12-21 22:12 UTC, jdolitsky submitted a review, later dismissed

2023-12-21 22:51 UTC, sudo-bmitch requested changes
Just one typo nit. Otherwise LGTM.

2023-12-21 22:51 UTC, sudo-bmitch commented on spec.md
> +If the `artifactType` is empty or missing in an index, the `arfactType` MUST be omitted.
```suggestion
If the `artifactType` is empty or missing in an index, the `artifactType` MUST be omitted.
```

2023-12-22 19:30 UTC, sajayantony commented
Thanks @sudo-bmitch @jdolitsky PTAL.

2023-12-22 19:32 UTC, sudo-bmitch approved these changes
LGTM

2023-12-22 21:07 UTC, jdolitsky approved these changes

2023-12-22 21:07 UTC, merged